import './globals.css'

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Image from 'next/image'

import logoImg from '../assets/logo.svg'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex min-h-screen flex-col items-start justify-center">
          <header className="mx-auto w-full max-w-[1180px] px-0 py-8">
            <Image src={logoImg} alt="" />
          </header>
          {children}
        </div>
      </body>
    </html>
  )
}
